  
name: makepkg CI

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
   # branches: 
   # - master
  schedule:
    - cron: 00 */6 * * *
  watch:
    types: [started]

jobs:
  build-package:
    strategy:
      matrix:
        arch: ["armv7", "aarch64"]
        repo: ["alarm", "aur", "community", "core", "extra"]
    runs-on: ubuntu-latest
    name: Build ${{ matrix.repo }} on ${{ matrix.arch }}
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      UPSTREAM_URL: ${{ secrets.UPSTREAM_URL }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Pull upstream changes
      uses: atomlong/Sync-With-Upstream-action@master
      id: sync
      if: ${{ env.UPSTREAM_URL != '' }}
      with:
        upstream_repository: ${{ env.UPSTREAM_URL }}
        upstream_branch: master
        target_branch: master
        git_push_args: --force-with-lease
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run on Archlinuxarm
      uses: atomlong/run-on-arch-action@alarm
      id: runcmd
      with:
        arch: ${{ matrix.arch }}
        githubToken: ${{ github.token }}
        rcloneConfig: ${{ secrets.RCLONE_CONF }}
        pgpKey: ${{ secrets.PGP_KEY }}
        pgpKeyPassword: ${{ secrets.PGP_KEY_PASSWD }}
        pacmanRepo: ""
        deployPath: onedrive:mirrors/archlinuxarm/${PACMAN_ARCH}
        run: |
          export PACMAN_REPO=${{ matrix.repo }}
          bash .github/workflows/ci-build.sh
          exit 0
    - name: Send mail
      uses: atomlong/send-mail-action@v2
      if: ${{ steps.runcmd.outputs.pkgfile0 != '' }}
      with:
        server_address: ${{secrets.MAIL_HOST}}
        server_port: ${{secrets.MAIL_PORT}}
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job of ${{github.repository}} result
        body: |
          <p>Successfully created the following package archive.</p>
          <p>Package: ${{ steps.runcmd.outputs.pkgfile0 }}</p>
        to: ${{secrets.MAIL_TO}}
        from: Github
        content_type: text/html
